version: "2.1"

services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:5.1.2
    container_name: zookeeper-1
    hostname: zookeeper-1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
    
  drill:
    image: harisekhon/apache-drill
    container_name: drill
    hostname: drill
    ports: 
      - 8047:8047
    command: ['supervisord', '-n']  
    environment:
      - ZOOKEEPER_HOST=zookeeper-1:2181
    restart: always

  presto:
    hostname: presto
    image: 'starburstdata/presto:302-e.7'
    container_name: presto
    ports:
      - '8089:8080'
    volumes: 
#      - './conf/presto/minio.properties:/usr/lib/presto/etc/catalog/minio.properties'
      - './conf/presto/postgresql.properties:/usr/lib/presto/etc/catalog/postgresql.properties'
#      - './hadoop/lib/json-serde-1.3.8-jar-with-dependencies.jar:/usr/lib/presto/lib/plugin/hive-hadoop2/json-serde-1.3.8-jar-with-dependencies.jar'
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 38080:8080
    restart: always

  postgresql:
    image: postgres:10
    container_name: postgresql
    hostname: postgresql
    volumes: 
      - ./sql/create-driver.sql:/docker-entrypoint-initdb.d/create-driver.sql
    environment:
      POSTGRES_DB: sample
      POSTGRES_PASSWORD: sample
      POSTGRES_USER: sample
    restart: always

  ftp:
    image: stilliard/pure-ftpd
    container_name: ftp
    hostname: ftp
    environment:
#      - PUBLICHOST="192.168.25.134"
      - FTP_USER_NAME=order
      - FTP_USER_PASS=order
      - FTP_USER_HOME=/home/orderentry
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    restart: always
      
  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      # mqtt
      - "1883:1883"
      # amqp
      - "5672:5672"
      # ui
      - "8161:8161"
      # stomp
      - "61613:61613"
      # ws
      - "61614:61614"
      # jms
      - "61616:61616"
    volumes:
      - ./container-volume/activemq/data:/opt/activemq/data
    restart: always
 
  hawtio:
    image: "indigo/hawtio"
    container_name: hawtio
    hostname: hawtio
    ports:
      - "8090:8090" 

