version: "2.1"

services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:5.1.2
    container_name: zookeeper-1
    hostname: zookeeper-1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
    
  drill:
    image: harisekhon/apache-drill
    container_name: drill
    hostname: drill
    ports: 
      - 8047:8047
    command: ['supervisord', '-n']  
    environment:
      - ZOOKEEPER_HOST=zookeeper-1:2181
    restart: always

  presto:
    image: starburstdata/presto
    container_name: presto
    hostname: presto
    ports:
      - 28080:8080
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 38080:8080
    restart: always

  mysql:
    image: mujz/pagila
    container_name: mysql
    environment:
      - POSTGRES_PASSWORD=sample
      - POSTGRES_USER=sample
      - POSTGRES_DB=sample
    restart: always

  ftp:
    image: stilliard/pure-ftpd
    container_name: ftp
    hostname: ftp
    environment:
#      - PUBLICHOST="192.168.25.134"
      - FTP_USER_NAME=order
      - FTP_USER_PASS=order
      - FTP_USER_HOME=/home/orderentry
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    restart: always
      
  activemq:
    image: rmohr/activemq:5.15.4
    container_name: activemq
    hostname: activemq
    ports:
      - 61616:61616
      - 8161:8161
    volumes:
      - ./container_data/activemq/data:/opt/activemq/data
#      - ./container_data/activemq/conf:/opt/activemq/conf
    restart: always
 
  hawtio:
    image: "indigo/hawtio"
    container_name: hawtio
    hostname: hawtio
    ports:
      - "8090:8090" 

