version: "2.1"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0-beta30-1
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
    
  drill:
    image: harisekhon/apache-drill
    hostname: drill
    ports: 
      - 8047:8047
    command: ['supervisord', '-n']  
    environment:
      - ZOOKEEPER_HOST=zookeepr:2181
    restart: always

  presto:
    image: starburstdata/presto:0.195-e.0.2
    hostname: presto
    ports:
      - 28080:8080
    restart: always

  adminer:
    image: adminer
    ports:
      - 38080:8080
    restart: always

  db:
    image: mujz/pagila
    environment:
      - POSTGRES_PASSWORD=sample
      - POSTGRES_USER=sample
      - POSTGRES_DB=sample
    restart: always
      